<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DetailIndicateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailIndicateurRepository extends EntityRepository
{
    public function findByIndicateur($id){
        $qb = $this->createQueryBuilder('d')
            ->leftJoin('d.indicateur','indicateur')
            ->where('d.indicateur=:id')
            ->setParameter('id',$id)
            ->orderBy('d.date','DESC');
        return $qb->getQuery()->getArrayResult();
    }
}
